-- Migration number: 0001 	 2024-01-22T00:00:00.000Z
-- Autogenerated migration for Projects table

CREATE TABLE IF NOT EXISTS Projects (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    imageUrl TEXT NOT NULL,
    publishedAt TEXT NOT NULL
);
